name: CI
on: [push]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: checkout code
      uses: actions/checkout@v1

    - name: lint
      run: make lint

  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-22.04]
        toolchain: ["stable", "nightly"]

    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: checkout code
      uses: actions/checkout@v1

    - name: test
      run: make test
