name: tests
on: [push]
jobs:

  build:
    name: tests

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        toolchain: ["stable", "nightly"]

    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: rustfmt, clippy

    - name: checkout code
      uses: actions/checkout@v1

    - name: lint
      run: make lint

    - name: test
      run: make test
